Feria/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('FeriaVirtual.urls')),
    path('Extranjero/', include('Extranjero.urls')),
    path('Local/', include('Local.urls')),
    path('Productor/', include('Productor.urls')),
    path('Transporte/', include('Transporte.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

FeriaVirtual/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home,name="Home"),
    path('nosotros/',views.nosotros, name="Nosotros"),
    path('contacto/',views.contacto, name="Contacto"),
    path('registro/',views.registro, name="Registro"),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Extranjero/models.py
from django.db import models

# Create your models here.
class DetalleSolicitud(models.Model):
    detalle_id = models.BigIntegerField(primary_key=True)
    producto = models.CharField(max_length=50)
    unidad_medida = models.CharField(max_length=20)
    solicitud_solicitud = models.ForeignKey('Solicitud', models.DO_NOTHING)
    cantidad = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'detalle_solicitud'

class Solicitud(models.Model):
    solicitud_id = models.BigIntegerField(primary_key=True)
    estado = models.CharField(max_length=10)
    fecha_solicitud = models.DateField()
    cliente_cliente = models.ForeignKey('Cliente', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'solicitud'

class Cliente(models.Model):
    cliente_id = models.BigIntegerField(primary_key=True)
    estado = models.CharField(max_length=10)
    email = models.CharField(max_length=50)
    contrasenia = models.CharField(max_length=200)
    rut_cliente = models.IntegerField()
    dv_cliente = models.CharField(max_length=5)
    fecha_alta = models.DateField()
    razon_social = models.CharField(max_length=50, blank=True, null=True)
    nombre = models.CharField(max_length=50, blank=True, null=True)
    ap_paterno = models.CharField(max_length=50, blank=True, null=True)
    ap_materno = models.CharField(max_length=50, blank=True, null=True)
    codigo_postal = models.CharField(max_length=15)
    direccion = models.CharField(max_length=100)
    comuna = models.CharField(max_length=50, blank=True, null=True)
    region = models.CharField(max_length=50, blank=True, null=True)
    pais = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'cliente'

FeriaVirtual/models.py
from django.db import models

# Create your models here.

FeriaVirtual/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.

def home(request):
    return render(request, "FeriaVirtual/home.html")

def nosotros(request):
    return render(request, "FeriaVirtual/nosotros.html")

def contacto(request):
    return render(request, "FeriaVirtual/contacto.html")

def registro(request):

    if request.method=="POST":
        
        subject=request.POST["nombre"]+request.POST["paterno"]
        message=request.POST["rsocial"]+"\n"+request.POST["mail"]+"\n"+request.POST["rut"]+"-"+request.POST["dvrut"]+"\n"+request.POST["pais"]+"\n"+request.POST["rol"]
        email_from=settings.EMAIL_HOST_USER
        recipient_list=["empresa.maipogrande@gmail.com"]
        send_mail(subject, message, email_from, recipient_list)
    
    return render(request,"FeriaVirtual/registro.html")
    

FeriaVirtual/templates/FeriaVirtual/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Feria Virtual | Home</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <!-- Favicons -->
  <link href="{% static 'FeriaVirtual/img/favicon.png' %}" rel="icon">
  <link href="{% static 'FeriaVirtual/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  <!-- Vendor CSS Files -->
  <link href="{% static 'FeriaVirtual/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'FeriaVirtual/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'FeriaVirtual/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'FeriaVirtual/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'FeriaVirtual/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{% static 'FeriaVirtual/css/main.css' %}" rel="stylesheet">
</head>

<body>

    <!-- ======= Header ======= -->
    <section id="topbar" class="topbar d-flex align-items-center">
        <div class="container d-flex justify-content-center justify-content-md-between">
          <div class="contact-info d-flex align-items-center">
            <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:contact@example.com">empresa.maipogrande@gmail.com</a></i>
          </div>
        </div>
    </section>
    
    <header id="header" class="header d-flex align-items-center">
    
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
          <a href="{% url 'Home' %}" class="logo d-flex align-items-center">
            {% if user.is_authenticated %}
              <h1>Feria Virtual | @{{ user.username}}</h1>
            {% endif %}
          </a>
         
          <nav id="navbar" class="navbar">
            <ul>
              <li class="{% if request.path == '/' %}active{% endif%}"><a href="{% url 'Home' %}">Home</a></li>
              <li class="{% if request.path == '/Nosotros' %}active{% endif%}"><a href="{% url 'Nosotros' %}">Nosotros</a></li>
              <li class="{% if request.path == '/Contacto' %}active{% endif%}"><a href="{% url 'Contacto' %}">Contacto</a></li>
              <li class="{% if request.path == '/Registro' %}active{% endif%}"><a href="{% url 'Registro' %}">Registro</a></li>
              {% if perms.Extranjero.add_solicitud%}
              <li class="{% if request.path == '/Extranjero' %}active{% endif%}"><a href="{% url 'Extranjero' %}">Extranjero</a></li>
              {% endif %}
              <li class="{% if request.path == '/Local' %}active{% endif%}"><a href="{% url 'Local' %}">Local</a></li>  
              <li class="{% if request.path == '/Productor' %}active{% endif%}"><a href="{% url 'Productor' %}">Productor</a></li>
              <li class="{% if request.path == '/Transporte' %}active{% endif%}"><a href="{% url 'Transporte' %}">Transporte</a></li>
              {% if user.is_authenticated %}
              <li class=""><a href="{% url 'logout'%}"><i class="bx bx-server"></i>Cerra Sesión</a></li>
              {% endif %}
            </ul>
          </nav>
    
          <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
          <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
    
        </div>
    </header>
     
    {% block content %}

    {% endblock %}

    <footer id="footer" class="footer">

        <div class="container">
          <div class="row gy-4">
            <div class="col-lg-5 col-md-12 footer-info">
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3329.6134399180605!2d-70.6177833848011!3d-33.433321080778924!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662cf7b8af466fd%3A0xc8fd2d768e783103!2sDuoc%20UC%3A%20Antonio%20Varas!5e0!3m2!1ses-419!2scl!4v1624814497158!5m2!1ses-419!2scl" frameborder="0" style="border:0; width: 100%; height: 290px;" allowfullscreen></iframe>
            </div>
    
            <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
              <h4>Contacto</h4>
              <p>
                Av.Antonio Varas #666 <br>
                Providencia, RM<br>
                Chile <br><br>
                <strong>Telefono:</strong> +569 2222 2222<br>
                <strong>Email:</strong> empresa.maipogrande@gmail.com<br>
              </p>
    
            </div>
    
          </div>
        </div>
    
        <div class="container mt-4">
          <div class="copyright">
            &copy; Copyright <strong><span>SSN</span></strong>.
          </div>
          <div class="credits">
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
          </div>
        </div>
    
    </footer>
        
      <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    
      <div id="preloader"></div>
    
      <!-- Vendor JS Files -->
      <script src="{% static 'FeriaVirtual/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'FeriaVirtual/vendor/aos/aos.js' %}"></script>
      <script src="{% static 'FeriaVirtual/vendor/glightbox/js/glightbox.min.js' %}"></script>
      <script src="{% static 'FeriaVirtual/vendor/purecounter/purecounter_vanilla.js' %}"></script>
      <script src="{% static 'FeriaVirtual/vendor/swiper/swiper-bundle.min.js' %}"></script>
      <script src="{% static 'FeriaVirtual/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
      <script src="{% static 'FeriaVirtual/vendor/php-email-form/validate.js' %}"></script>
    
      <!-- Template Main JS File -->
      <script src="{% static 'FeriaVirtual/js/main.js' %}"></script>

</body>
</html>

FeriaVirtual/templates/FeriaVirtual/contacto.html
{% extends "FeriaVirtual/base.html" %}
{% load static %}

{% block content %}
<section id="blog" class="blog">
  <div class="container" data-aos="fade-up">
    <div class="row">
      <div class="">
        <div class="comments">
          <h4 class="comments-count">Contactanos</h4>
          <div class="reply-form">
            <p>Por este medio podras solucionar tus dudas o consulas.</p>
            <form action="">
              <div class="row">
                <div class="col-md-6 form-group">
                  <input name="name" type="text" class="form-control" placeholder="Your Name*">
                </div>
                <div class="col-md-6 form-group">
                  <input name="email" type="text" class="form-control" placeholder="Your Email*">
                </div>
              </div>
              <div class="row">
                <div class="col form-group">
                  <input name="website" type="text" class="form-control" placeholder="Your Website">
                </div>
              </div>
              <div class="row">
                <div class="col form-group">
                  <textarea name="comment" class="form-control" placeholder="Your Comment*"></textarea>
                </div>
              </div>
              <button type="submit" class="btn btn-primary">Post Comment</button>
            </form>
          </div>
        </div><!-- End blog comments -->
      </div>
    </div>
  </div>
</section><!-- End Blog Details Section -->
{% endblock %}

FeriaVirtual/templates/FeriaVirtual/home.html
{% extends "FeriaVirtual/base.html" %}
{% load static %}

{% block content %}

  <section id="hero" class="hero">
    <div class="container position-relative">
      <div class="row gy-5" data-aos="fade-in">
        <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center text-center text-lg-start">
          <h2><span>Maipo Grande</span></h2>
          <p>Si la vida no te sonrie, agregale mas FRUTA.</p>
          <br>
          <div class="d-flex justify-content-center justify-content-lg-start">
            <a href="{% url 'login'%}" class="btn-get-started">Iniciar Sesion</a>
            
          </div>
        </div>
        <div class="col-lg-6 order-1 order-lg-2">
          <img src="assets/img/hero-img.svg" class="img-fluid" alt="" data-aos="zoom-out" data-aos-delay="100">
        </div>
      </div>
    </div>

    <div class="icon-boxes position-relative">
      <div class="container position-relative">
        <div class="row gy-4 mt-5">

          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="100">
            <div class="icon-box">

            </div>
          </div>
          <!--End Icon Box -->

          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="200">
            <div class="icon-box">

            </div>
          </div>
          <!--End Icon Box -->

          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="300">
            <div class="icon-box">

            </div>
          </div>
          <!--End Icon Box -->

          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="500">
            <div class="icon-box">

            </div>
          </div>
          <!--End Icon Box -->

        </div>
      </div>
    </div>
  </section>

{% endblock %}

FeriaVirtual/templates/FeriaVirtual/nosotros.html
{% extends "FeriaVirtual/base.html" %}
{% load static %}

{% block content %}

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="page-header d-flex align-items-center" style="background-image: url('');">
        <div class="container position-relative">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-6 text-center">
              <h2>Sobre Nosotros</h2>
              <p>Aqui plasmamos nuestra mision y vision.</p>
            </div>
          </div>
        </div>
      </div>
      <nav>
        <div class="container">
          <ol>
            <li><a href="{% url 'Home' %}">Home</a></li>
            <li>Nosotros</li>
            <li>Mision</li>
            <li>Vision</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Portfolio Details Section ======= -->
    <section id="portfolio-details" class="portfolio-details">
      <div class="container" data-aos="fade-up">
        <div class="row justify-content-between gy-4 mt-4">
          <div class="col-lg-8">
            <div class="portfolio-description">
              <h2>Nosotros</h2>
              <p>
                Somos una empresa que agrupa a variados agricultores a nivel nacional, sin importar su tamaño, ya sea pequeña, mediana y empresas posicionadas a nivel nacional por sobre todo de la region metropolitana.
                El proposito de la empresa es reducir las mermas de nuestros productores, aumentar las ventas de nuestros productores asociados y llegar a clientes los cuales por si solos no pueden llegar, abarcando tanto clientes a nivel nacional como internacional, en pocas palabras dar una solucion rapida y centralizada para la venta y distribucion de toda la produccion de nuestros productores y agricultores asociados a nuestros clientes.
              </p>
              <p>
                Valores

                Liderazgo 	: Esforzarnos cada dia para dar forma a un futuro mejor para nuestros Productores, Clientes y Transportistas.
                Colaboracion 	: Potenciar dia a dia a cada uno de nuestros asociados.
                Integridad 	: Ser una empresa 100% transparente.
                Pasion		: Ser una empresa 100% comprometida con todos nuestros Productores, Clientes y Transportistas.
                Diversidad	: Contar con un amplio Stock de frutas para todos nuestros Clientes.
                Calidad		: Buscar y ofrecer la mejor fruta para nuestros Clientes, tanto nacional como internacional.
              </p>

              <div class="testimonial-item">
                <p>
                  <i class="bi bi-quote quote-icon-left"></i>
                  Realizar la venta de toda la mayor parte de la fruta de nuestros productores asociados, ya sea venta nacional e internacional, dar un valor agregado a nuestros productores, reducir sus costos operativos tales como almacenamiento, mantenimiento y dar soluciones tecnologicas a nuestros Agricultores, Clientes, Transportistas, y clientes asociados a nuestras plataformas.
                  <i class="bi bi-quote quote-icon-right"></i>
                </p>
                <div>
                  <img src="assets/img/testimonials/testimonials-2.jpg" class="testimonial-img" alt="">
                  <h3>Mision</h3>
                  <h4>Maipo Grande</h4>
                </div>
              </div>
              <div class="testimonial-item">
                <p>
                  <i class="bi bi-quote quote-icon-left"></i>
                  
Ser la Empresa que agrupe a la mayor cantidad de productores de frutas para tener la red mas grande a nivel nacional y ayudar a nuestros productores nacionales a comercialidad la totalidad de su fruta y minimizar al maximo posible la perdida de fruta.
                  <i class="bi bi-quote quote-icon-right"></i>
                </p>
                <div>
                  <img src="assets/img/testimonials/testimonials-2.jpg" class="testimonial-img" alt="">
                  <h3>Vision</h3>
                  <h4>Maipo Grande</h4>
                </div>
            </div>
          </div>
        </div>
      </div>
    </section><!-- End Portfolio Details Section -->

 

  {% endblock %}

FeriaVirtual/templates/FeriaVirtual/registro.html
{% extends "FeriaVirtual/base.html" %}
{% load static %}

{% block content %}

<body class="main-bg">
  <div class="login-container text-c animated flipInX">
    <div class="container-content">
      <h3 class="text-whitesmoke">Resgistrate llenando y enviando el formulario.</h3>
      <form action="" method="POST" class="margin-t">{% csrf_token %}
        <div class="row">
          <div class="col-lg-6">
            <ul>
              <div class="form-group">
                <label for="nombre" >Nombre</label>
                <input name="nombre" required type="text" id="r_nombre" class="form-control" value="">
              </div>
              <div class="form-group">
                <label for="paterno" >Apellido Paterno</label>
                <input name="paterno" required type="text" id="r_paterno" class="form-control" value="">
              </div>
              <div class="form-group">
                <label for="mateno" >Apellido Materno (opcional)</label>
                <input name="materno" required type="text" id="r_materno" class="form-control" value="">
              </div>
              <div class="form-group">
                <label for="rut" >RUT</label>
                <input name="rut" required type="text" id="r_rut" class="form-control" value="">
              </div>
              <div class="form-group">
                <label for="dvrut" >Digito verificador</label>
                <input name="dvrut" required type="text" id="r_dvrut" class="form-control" value="">
              </div>
              <div class="form-group">
                <label for="mail" >E-mail</label>
                <input name="mail" required type="mail"  type="text" id="r_mail" class="form-control" value="">
              </div>
              <div class="form-group">
                <label for="rsocial" >Razon social</label>
                <input name="rsocial" required type="text" id="r_social" class="form-control" value="">
              </div>
            </ul>
          </div>
          <div class="col-lg-6">
            <ul>
              <div class="form-group">
                <label for="direccion" >Direccion</label>
                <input name="direccion" required type="text" id="r_direccion" class="form-control" value="">
              </div>
              <div class="form-group">
                <label for="comuna" >Comuna</label>
                <input name="comuna" required type="text" id="r_comuna" class="form-control" value="">
              </div>
              <div class="form-group">
                <label for="region">Region</label>
                <input name="region" required type="text" id="r_region" class="form-control" value=""> 
              </div>
              <div class="form-group">
                <label for="pais">Pais</label>
                <input name="pais" required type="text" id="r_pais" class="form-control" value=""> 
              </div>
              <div class="form-group">
                <label for="codigo" >Codigo Postal</label>
                <input name="codigo" required type="number" id="r_codigo" class="form-control" value=""> 
              </div>
              <div class="form-group">
                <label for="rol" >Rol Usuario</label>
                <select required type="text" id="r_rol" name="rol" class="form-control">
                  <option hidden selected>Selecciona...</option>
                  <option  value="trasnporte">Transporte</option>
                  <option  value="comprar_nacional">Compra Nacional</option>
                  <option  value="comprar_internacional">Compra Internacional</option>
                  <option  value="vender">Vender</option>
                </select>
              </div>                  
            </ul>
          </div>
        </div>
        <button type="submit" class="form-button button-l margin-b">Enviar</button>
      </form>
    </div>
  </div>
</body>
{% endblock %}